config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  resources :posts, only: %i[show index]
  resources :tags, only: [:show]
  resources :categories, only: [:show]

  namespace :admin do
    resources :posts, except: %i[show index]
    resources :categories, except: [:show]
    resources :pictures, only: %i[create destroy]
  end
end

app/models/category.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  ancestry   :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Category < ApplicationRecord
  has_many :posts

  has_ancestry

  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

class Admin::CategoriesController < Admin::AdminController
  before_action :set_category, only: %i[edit update destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
    @categories = Category.all.order(:name)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, success: 'Категорію успішно створено'
    else
      @categories = Category.all.order(:name)
      flash[:danger] = 'Категорію не створено'
      render :new
    end
  end

  def edit
    @categories = Category.where("id != #{@category.id}").order(:name)
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to admin_categories_path, success: 'Категорію успішно оновлено'
    else
      @categories = Category.where("id != #{@category.id}").order(:name)
      flash[:danger] = 'Категорію не оновлено'
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_path, success: 'Категорію успішно видалено'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :parent_id)
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: :show

  def show
    @posts = Post.where(category_id: [@category.subtree_ids]).paginate(page: params[:page], per_page: 5)
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/views/admin/categories/_error.html.slim
- if @category.errors.any?
  #error_explanation.alert.alert-danger
    h5
      = t("common.errors")
    ul
      - @category .errors.full_messages.each do |msg|
        li
          = msg

app/views/admin/categories/_form.html.slim
= form_for [:admin, @category] do |f|
  = render "error"
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :parent_id
    = f.collection_select :parent_id, @categories, :id, :name, { include_blank: true }, class: "form-control"
  .form-group
    = f.submit t(".submit", action: @category.new_record? ? t("common.create") : t("common.change")), class: "btn btn-primary"
    = link_to t("common.back"), :back, class: "btn btn-outline-secondary"

app/views/admin/categories/edit.html.slim
h1
  = t(".title")
= render "form"

app/views/admin/categories/index.html.slim
h1
  = t(".title")
.buttons_panel
  = link_to t("admin.categories.new.title"), new_admin_category_path, class: "btn btn-outline-primary btn-sm"
section#categories
  table.table
    thead
      tr
        th
          = t(".table.th1")
        th
          = t(".table.th2")
        th
          = t(".table.th3")
        th
          = t(".table.th4")
    tbody
      - @categories.each_with_index do |category, index |
        tr
          td
            = index + 1
          td
            = category.name
          td
            = category.parent.name if category.parent.present?
          td
            = link_to t("common.change"), edit_admin_category_path(category), class: "btn btn-outline-primary btn-sm"
            = link_to t("common.delete"), admin_category_path(category), method: :delete, data: { confirm: t("categories.form.confirm")}, class: "btn btn-outline-danger btn-sm"

app/views/admin/categories/new.html.slim
h2
  = t(".title")
= render "form"