config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  resources :posts, only: %i[show index]
  resources :tags, only: [:show]
  resources :categories, only: [:show]

  namespace :admin do
    resources :posts, except: %i[show index]
    resources :categories, except: [:show]
    resources :pictures, only: %i[create destroy]
  end
end

app/models/post.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  body        :text
#  image       :string
#  summary     :text
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#
# Indexes
#
#  index_posts_on_category_id  (category_id)
#
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  belongs_to :category

  validates :title, :summary, :body, presence: true

  def all_tags
    tags.map(&:name).join(', ')
  end

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
end

app/controllers/admin/posts_controller.rb
# frozen_string_literal: true

class Admin::PostsController < Admin::AdminController
  before_action :set_post, only: %i[edit update destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, success: 'Допис успішно створено'
    else
      flash.now[:danger] = 'Допис не створено'
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to @post, success: 'Допис успішно оновлено'
    else
      flash.now[:danger] = 'Допис не оновлено'
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, success: 'Допис успішно видалено'
  end

  private

  def post_params
    params.require(:post).permit(:title, :summary, :body, :image, :all_tags, :category_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: :show

  def index
    @posts = Post.paginate(page: params[:page], per_page: 5)
  end

  def show; end

  private

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def tag_cloud(tags, classes)
    max = tags.max_by(&:count)
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end
end

app/views/posts/_delimeter.html.slim
.page_delimeter
  | Page
  = params[:page]

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

  /**
   *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
   *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
  /*
  var disqus_config = function () {
  this.page.url = PAGE_URL;  // Replace PAGE_URL with your page"s canonical URL variable
  this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page"s unique identifier variable
  };
  */
  var disqus_config = function () {

<!--    this.page.url = "<%#= request.base.url +  request.original_fullpath %>;-->
    this.page.url = "http://localhost.com<%= request.original_fullpath %>";
    this.page.identifier = "<%= @post.id %>";
  };
  (function() { // DON"T EDIT BELOW THIS LINE
    var d = document, s = d.createElement("script");
    s.src = "https://my-blog-on-rails.disqus.com/embed.js";
    s.setAttribute("data-timestamp", +new Date());
    (d.head || d.body).appendChild(s);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_error.html.erb
<% if @post.errors.any? %>
  <div id='error_explanation' class='alert alert-danger'>
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<%end %>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <%= render "error" %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.trix_editor :body, class: "editor" %>
  </div>

  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name, { include_blank: true},class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :all_tags %>
    <%= f.text_field :all_tags, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <%= f.submit t(".submit", action: @post.new_record? ? t("common.create") : t("common.change")), class: "btn btn-primary" %>
    <%= link_to t("common.back"), :back, class: "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/posts/_post.html.slim
article.post
  section.post-head
    h2
      = link_to post.title, post_path(post)
    small
      time
        = post.created_at.to_date.strftime('%d %B, %Y')
      - if post.category.present?
        |  |
        = link_to post.category.name, post.category
      - if user_signed_in? && current_user.admin?
        |  |
        = link_to t('common.change'), edit_admin_post_path(post)
        |  |
        = link_to t('common.delete'), admin_post_path(post), method: :delete, data: { confirm: t('admin.posts.form.confirm') }
  section.post-summary.clearfix
    = image_tag post.image.url(:thumb), class: 'img-thumbnail thumb' if post.image?
    = post.summary
  section.footer-summary
    = raw post.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: "btn btn-primary btn-sm" }.join(' ')

app/views/posts/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/posts/index.html.slim
h1
  = t(".title")
section#posts
  = render @posts
= will_paginate @posts, renderer: "BootstrapPaginationHelper::LinkRenderer"

app/views/posts/index.js.erb
$("#posts").append("<%= j render(partial: "delimeter") %>");
$("#posts").append("<%= j render(@posts) %>");

<% if @posts.next_page %>
  $(".pagination").replaceWith("<%= j  will_paginate(@posts, renderer: "BootstrapPaginationHelper::LinkRenderer") %>");
<% else %>
  $(".pagination").remove();
<% end %>

app/views/posts/new.html.erb
<h2><%= t('.title') %></h2>

<%= render 'form' %>

app/views/posts/show.html.slim
= render "shared/breadcrumb", category: @post.category
article.post
  section.post-head
    h1
      = @post.title
    small
      time
        = @post.created_at.to_date.strftime("%d %B, %Y")
      - if @post.category.present?
        |  |
        = link_to @post.category.name, @post.category
      - if user_signed_in? && current_user.admin?
        |  |
        = link_to t("common.change"), edit_admin_post_path(@post)
        |  |
        = link_to t("common.delete"), admin_post_path(@post), method: :delete, data: { confirm: t("admin.posts.form.confirm") }
  section.post-summary
    = image_tag @post.image.url(:large), class: "img-show" if @post.image?
    = @post.body.html_safe
= render "disqus"