config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  resources :posts, only: %i[show index]
  resources :tags, only: [:show]
  resources :categories, only: [:show]

  namespace :admin do
    resources :posts, except: %i[show index]
    resources :categories, except: [:show]
    resources :pictures, only: %i[create destroy]
  end
end

app/models/category.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  ancestry   :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Category < ApplicationRecord
  has_many :posts

  has_ancestry

  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

class Admin::CategoriesController < Admin::AdminController
  before_action :set_category, only: %i[edit update destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
    @categories = Category.all.order(:name)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, success: 'Категорію успішно створено'
    else
      @categories = Category.all.order(:name)
      flash[:danger] = 'Категорію не створено'
      render :new
    end
  end

  def edit
    @categories = Category.where("id != #{@category.id}").order(:name)
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to admin_categories_path, success: 'Категорію успішно оновлено'
    else
      @categories = Category.where("id != #{@category.id}").order(:name)
      flash[:danger] = 'Категорію не оновлено'
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_path, success: 'Категорію успішно видалено'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :parent_id)
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: :show

  def show
    @posts = Post.where(category_id: [@category.subtree_ids]).paginate(page: params[:page], per_page: 5)
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <%= render "error" %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :parent_id %>
    <%= f.collection_select :parent_id, @categories, :id, :name, { include_blank: true }, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit t(".submit", action: @category.new_record? ? t("common.create") : t("common.change")), class: "btn btn-primary" %>
    <%= link_to t("common.back"), :back, class: "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/categories/index.html.erb
<h1><%= t(".title") %></h1>

<div class="buttons_panel">
  <%= link_to t("categories.new.title"), new_category_path, class: "btn btn-outline-primary btn-sm" %>
</div>

<section id="categories">
  <table class="table">
    <thead>
    <tr>
      <th><%= t(".table.th1") %></th>
      <th><%= t(".table.th2") %></th>
      <th><%= t(".table.th3") %></th>
      <th><%= t(".table.th4") %></th>
    </tr>
    </thead>
    <tbody>
      <% @categories.each_with_index do |category, index | %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= category.name %></td>
        <td><%= category.parent.name if category.parent.present? %></td>
        <td>
          <%= link_to t("common.change"), edit_category_path(category), class: "btn btn-outline-primary btn-sm" %>
          <%= link_to t("common.delete"), category_path(category), method: :delete, data: { confirm: t("categories.form.confirm")}, class: "btn btn-outline-danger btn-sm" %>          </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/categories/show.html.slim
= render "shared/breadcrumb", category: @category
h1
  = @category.name
section#posts
  = render @posts
= will_paginate @posts, renderer: "BootstrapPaginationHelper::LinkRenderer"

app/views/categories/show.js.erb
$("#posts").append("<%= j render(partial: "posts/delimeter") %>");
$("#posts").append("<%= j render(@posts) %>");

<% if @posts.next_page %>
$(".pagination").replaceWith("<%= j  will_paginate(@posts, renderer: "BootstrapPaginationHelper::LinkRenderer") %>");
<% else %>
$(".pagination").remove();
<% end %>